
import React from 'react';
import { Department, ToolStatus } from './types';

export const DEPARTMENTS = Object.values(Department);

export const DEPARTMENT_LABELS: Record<Department, string> = {
  [Department.RPL]: 'Rekayasa Perangkat Lunak',
  [Department.DKV]: 'Desain Komunikasi Visual',
  [Department.TKJ]: 'Teknik Komputer & Jaringan',
  [Department.TPM]: 'Teknik Pemesinan',
  [Department.TPL]: 'Teknik Pengelasan',
  [Department.TKR]: 'Teknik Kendaraan Ringan',
  [Department.TAB]: 'Teknik Alat Berat',
  [Department.TSM]: 'Teknik Sepeda Motor',
  [Department.TBO]: 'Teknik Bodi Otomotif'
};

export const INITIAL_TOOLS = [
  { id: '1', name: 'Laptop ASUS ROG', department: Department.RPL, quantity: 10, availableQuantity: 8, status: ToolStatus.AVAILABLE, location: 'Lab RPL 1', notes: 'Kondisi prima' },
  { id: '2', name: 'Kamera Sony A7III', department: Department.DKV, quantity: 5, availableQuantity: 3, status: ToolStatus.AVAILABLE, location: 'Studio DKV', notes: 'Lensa kit 28-70mm' },
  { id: '3', name: 'Cisco Router 2911', department: Department.TKJ, quantity: 4, availableQuantity: 4, status: ToolStatus.AVAILABLE, location: 'Lab Jaringan', notes: 'Rack mounted' },
  { id: '4', name: 'Mesin Bubut CNC', department: Department.TPM, quantity: 2, availableQuantity: 2, status: ToolStatus.AVAILABLE, location: 'Bengkel TPM', notes: 'Tegangan tinggi' },
  { id: '5', name: 'Mesin Las Argon', department: Department.TPL, quantity: 8, availableQuantity: 6, status: ToolStatus.AVAILABLE, location: 'Bengkel Las', notes: 'Wajib APD' },
  { id: '6', name: 'Kunci T Set', department: Department.TKR, quantity: 20, availableQuantity: 15, status: ToolStatus.AVAILABLE, location: 'Bengkel TKR', notes: 'Merk Tekiro' },
];

export const TRANSLATIONS = {
  id: {
    dashboard: 'Dashboard',
    inventory: 'Inventaris Alat',
    lending: 'Peminjaman',
    reports: 'Laporan',
    settings: 'Pengaturan',
    logout: 'Keluar',
    total_tools: 'Total Alat',
    tools_borrowed: 'Alat Dipinjam',
    pending_requests: 'Permintaan Pending',
    in_maintenance: 'Dalam Perbaikan',
    distribution_chart: 'Distribusi Alat per Jurusan',
    recent_lending: 'Peminjaman Terbaru',
    see_all: 'Lihat Semua',
    search_tools: 'Cari alat...',
    all_depts: 'Semua Jurusan',
    all_status: 'Semua Status',
    add_tool: 'Tambah Alat',
    name_photo: 'Nama & Foto',
    department: 'Jurusan',
    available: 'Tersedia',
    location: 'Lokasi',
    status: 'Status',
    actions: 'Aksi',
    pinjam: 'Pinjam',
    see_history: 'Lihat Riwayat',
    student_class: 'Siswa / Kelas',
    borrow_date: 'Tgl Pinjam',
    welcome: 'Selamat datang kembali, Admin SMK.',
    language: 'Bahasa',
    no_history: 'Belum ada riwayat peminjaman yang tercatat untuk alat ini.',
    total_records: 'Total Catatan',
    borrow_form: 'Form Peminjaman Alat',
    student_name: 'Nama Lengkap Siswa',
    class_label: 'Kelas',
    borrow_qty: 'Jumlah Pinjam',
    notes: 'Catatan Keperluan',
    cancel: 'Batal',
    submit_borrow: 'Ajukan Pinjam',
    edit_tool: 'Edit Detail Alat',
    add_new_tool: 'Tambah Alat Baru',
    save_changes: 'Simpan Perubahan',
    take_photo: 'Ambil Foto',
    open_camera: 'Buka Kamera',
    photo_preview: 'Preview Foto Alat',
    stock_label: 'Total Stok',
    tool_notes: 'Catatan Spesifikasi Alat',
    notes_placeholder: 'Contoh: Kondisi baik, merk tertentu, spesifikasi teknis...',
    bulk_actions: 'Aksi Massal',
    approve_selected: 'Setujui Terpilih',
    reject_selected: 'Tolak Terpilih',
    return_selected: 'Kembalikan Terpilih',
    items_selected: 'item terpilih',
    select_all: 'Pilih Semua'
  },
  en: {
    dashboard: 'Dashboard',
    inventory: 'Tool Inventory',
    lending: 'Lending',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    total_tools: 'Total Tools',
    tools_borrowed: 'Tools Borrowed',
    pending_requests: 'Pending Requests',
    in_maintenance: 'In Maintenance',
    distribution_chart: 'Tool Distribution by Department',
    recent_lending: 'Recent Lending',
    see_all: 'See All',
    search_tools: 'Search tools...',
    all_depts: 'All Departments',
    all_status: 'All Status',
    add_tool: 'Add Tool',
    name_photo: 'Name & Photo',
    department: 'Department',
    available: 'Available',
    location: 'Location',
    status: 'Status',
    actions: 'Actions',
    pinjam: 'Borrow',
    see_history: 'View History',
    student_class: 'Student / Class',
    borrow_date: 'Borrow Date',
    welcome: 'Welcome back, SMK Admin.',
    language: 'Language',
    no_history: 'No lending history recorded for this tool yet.',
    total_records: 'Total Records',
    borrow_form: 'Tool Lending Form',
    student_name: 'Full Student Name',
    class_label: 'Class',
    borrow_qty: 'Borrow Quantity',
    notes: 'Purpose / Notes',
    cancel: 'Cancel',
    submit_borrow: 'Submit Request',
    edit_tool: 'Edit Tool Details',
    add_new_tool: 'Add New Tool',
    save_changes: 'Save Changes',
    take_photo: 'Take Photo',
    open_camera: 'Open Camera',
    photo_preview: 'Tool Photo Preview',
    stock_label: 'Total Stock',
    tool_notes: 'Tool Specification Notes',
    notes_placeholder: 'e.g. Good condition, specific brand, technical specs...',
    bulk_actions: 'Bulk Actions',
    approve_selected: 'Approve Selected',
    reject_selected: 'Reject Selected',
    return_selected: 'Mark Returned',
    items_selected: 'items selected',
    select_all: 'Select All'
  }
};
